/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
   * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class bukuform extends javax.swing.JFrame {
    buku buku = new buku();
    /**
     * Creates new form bukuform
     */
    public bukuform() {
        initComponents();
        
        cbbuku.addItem("SD");
        cbbuku.addItem("SMP");
        cbbuku.addItem("SMA");
        
        nonaktif();
        bersih();
    }
    void aktif(){
        nmapembeli.setEnabled(true);
        cbbuku.setEnabled(true);
        ragama.setEnabled(true);
        rbahasainggris.setEnabled(true);
        rbahasaindonesia.setEnabled(true);
        rmatematika.setEnabled(true);
        rips.setEnabled(true);
        ripa.setEnabled(true);
        rppkn.setEnabled(true);
        rpjok.setEnabled(true);
        tharga.setEnabled(true);
        tjml.setEnabled(true);
        ttot.setEnabled(true);
        tubyr.setEnabled(true);
        tukemb.setEnabled(true);
    }
    void bersih(){
        nmapembeli.setText("");
        cbbuku.setSelectedItem("-PILIH-");
        buttonGroup1.clearSelection();
        tharga.setText("");
        tjml.setText("");
        ttot.setText("");
        tubyr.setText("");
        tukemb.setText("");
    }
    void nonaktif(){
        nmapembeli.setEnabled(false);
        cbbuku.setEnabled(false);
        ragama.setEnabled(false);
        rbahasainggris.setEnabled(false);
        rbahasaindonesia.setEnabled(false);
        rmatematika.setEnabled(false);
        ripa.setEnabled(false);
        rips.setEnabled(false);
        rppkn.setEnabled(false);
        rpjok.setEnabled(false);
        tharga.setEnabled(false);
        tjml.setEnabled(false);
        ttot.setEnabled(false);
        tubyr.setEnabled(false);
        tukemb.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nmapembeli = new javax.swing.JTextField();
        cbbuku = new javax.swing.JComboBox<>();
        ripa = new javax.swing.JRadioButton();
        rips = new javax.swing.JRadioButton();
        rppkn = new javax.swing.JRadioButton();
        rmatematika = new javax.swing.JRadioButton();
        ragama = new javax.swing.JRadioButton();
        rbahasaindonesia = new javax.swing.JRadioButton();
        rbahasainggris = new javax.swing.JRadioButton();
        rpjok = new javax.swing.JRadioButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();
        tjml = new javax.swing.JTextField();
        ttot = new javax.swing.JTextField();
        tubyr = new javax.swing.JTextField();
        tukemb = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        bhitung = new javax.swing.JButton();
        bbaru = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko Buku Emas");

        jPanel5.setBackground(new java.awt.Color(222, 188, 153));

        jPanel16.setBackground(new java.awt.Color(255, 245, 225));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(131, 38, 26));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUKU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel17.setForeground(new java.awt.Color(131, 38, 26));

        jLabel22.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("NAMA");

        jLabel23.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("JENJANG \nPENDIDIKAN");

        jLabel24.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("-JENIS BUKU-");

        nmapembeli.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        cbbuku.setBackground(new java.awt.Color(222, 188, 153));
        cbbuku.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cbbuku.setForeground(new java.awt.Color(131, 38, 26));
        cbbuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-" }));
        cbbuku.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbukuItemStateChanged(evt);
            }
        });
        cbbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbukuActionPerformed(evt);
            }
        });

        buttonGroup1.add(ripa);
        ripa.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        ripa.setForeground(new java.awt.Color(255, 255, 255));
        ripa.setText("IPA");
        ripa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ripaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rips);
        rips.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rips.setForeground(new java.awt.Color(255, 255, 255));
        rips.setText("IPS");
        rips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ripsActionPerformed(evt);
            }
        });

        buttonGroup1.add(rppkn);
        rppkn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rppkn.setForeground(new java.awt.Color(255, 255, 255));
        rppkn.setText("PPKN");
        rppkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rppknActionPerformed(evt);
            }
        });

        buttonGroup1.add(rmatematika);
        rmatematika.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rmatematika.setForeground(new java.awt.Color(255, 255, 255));
        rmatematika.setText("MATEMATIKA");
        rmatematika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmatematikaActionPerformed(evt);
            }
        });

        buttonGroup1.add(ragama);
        ragama.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        ragama.setForeground(new java.awt.Color(255, 255, 255));
        ragama.setText("AGAMA");
        ragama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ragamaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbahasaindonesia);
        rbahasaindonesia.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rbahasaindonesia.setForeground(new java.awt.Color(255, 255, 255));
        rbahasaindonesia.setText("BAHASA INDONESIA");
        rbahasaindonesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbahasaindonesiaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbahasainggris);
        rbahasainggris.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rbahasainggris.setForeground(new java.awt.Color(255, 255, 255));
        rbahasainggris.setText("BAHASA INGGRIS");
        rbahasainggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbahasainggrisActionPerformed(evt);
            }
        });

        buttonGroup1.add(rpjok);
        rpjok.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rpjok.setForeground(new java.awt.Color(255, 255, 255));
        rpjok.setText("PJOK");
        rpjok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpjokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rips)
                                .addComponent(ripa))
                            .addGap(96, 96, 96))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                            .addComponent(rppkn)
                            .addGap(83, 83, 83)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(rmatematika)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rpjok)
                    .addComponent(rbahasainggris)
                    .addComponent(rbahasaindonesia)
                    .addComponent(ragama))
                .addGap(65, 65, 65))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nmapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ripa)
                    .addComponent(ragama))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rips)
                    .addComponent(rbahasaindonesia))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rppkn)
                    .addComponent(rbahasainggris))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmatematika)
                    .addComponent(rpjok))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(131, 38, 26));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HARGA BUKU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("HARGA BUKU");

        jLabel26.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("JUMLAH BELI");

        jLabel27.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("UANG BAYAR");

        jLabel28.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("UANG KEMBALI");

        jLabel29.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("TOTAL BAYAR");

        tharga.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thargaActionPerformed(evt);
            }
        });

        tjml.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        ttot.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        ttot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotActionPerformed(evt);
            }
        });

        tubyr.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tubyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tubyrActionPerformed(evt);
            }
        });
        tubyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tubyrKeyPressed(evt);
            }
        });

        tukemb.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tukemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tukembActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tubyr, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tukemb, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(tubyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel28))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tukemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(131, 38, 26));

        bhitung.setBackground(new java.awt.Color(222, 188, 153));
        bhitung.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        bhitung.setForeground(new java.awt.Color(131, 38, 26));
        bhitung.setText("TOTAL");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });

        bbaru.setBackground(new java.awt.Color(222, 188, 153));
        bbaru.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        bbaru.setForeground(new java.awt.Color(131, 38, 26));
        bbaru.setText("BARU");
        bbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbaruActionPerformed(evt);
            }
        });

        bclose.setBackground(new java.awt.Color(222, 188, 153));
        bclose.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        bclose.setForeground(new java.awt.Color(131, 38, 26));
        bclose.setText("KELUAR");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jLabel30.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TOKO BUKU EMAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(345, 345, 345))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbukuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbukuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbukuItemStateChanged

    private void cbbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbukuActionPerformed

    private void ragamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ragamaActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiAgama();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_ragamaActionPerformed

    private void tukembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tukembActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tukembActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        buku.setHrg(Integer.parseInt(tharga.getText()));
        buku.setJml(Integer.parseInt(tjml.getText()));
        ttot.setText(Integer.toString(buku.getTtl()));
    }//GEN-LAST:event_bhitungActionPerformed

    private void bbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbaruActionPerformed
        aktif();
        bersih();
        nmapembeli.requestFocus();
    }//GEN-LAST:event_bbaruActionPerformed

    private void ripaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ripaActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiIpa();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_ripaActionPerformed

    private void ripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ripsActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiIps();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_ripsActionPerformed

    private void rppknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rppknActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiPpkn();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_rppknActionPerformed

    private void rmatematikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmatematikaActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiMatematika();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_rmatematikaActionPerformed

    private void rbahasaindonesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbahasaindonesiaActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiBahasaindonesia();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_rbahasaindonesiaActionPerformed

    private void rbahasainggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbahasainggrisActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiBahasainggris();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_rbahasainggrisActionPerformed

    private void rpjokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpjokActionPerformed
    buku.setJenjang(cbbuku.getSelectedItem().toString());
    buku.setSeleksiPjok();
    tharga.setText(Integer.toString(buku.getHrg()));
    }//GEN-LAST:event_rpjokActionPerformed

    private void ttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotActionPerformed

    private void thargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thargaActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
    this.setVisible(false);
    new mainmenu().setVisible(true);    
    }//GEN-LAST:event_bcloseActionPerformed

    private void tubyrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tubyrKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            buku.setUb(Integer.parseInt(tubyr.getText()));
            tukemb.setText(Integer.toString(buku.getUk()));
            if(buku.getUb()<buku.getTtl()){
                JOptionPane.showMessageDialog(null,"Pembayaran Kurang","Warning",JOptionPane.OK_OPTION);
                tukemb.setText("");
                tubyr.setText("");
            }
        else{
                return;
            }
        }
    }//GEN-LAST:event_tubyrKeyPressed

    private void tubyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tubyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tubyrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bukuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bukuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bukuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bukuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bukuform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbaru;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bhitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbuku;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nmapembeli;
    private javax.swing.JRadioButton ragama;
    private javax.swing.JRadioButton rbahasaindonesia;
    private javax.swing.JRadioButton rbahasainggris;
    private javax.swing.JRadioButton ripa;
    private javax.swing.JRadioButton rips;
    private javax.swing.JRadioButton rmatematika;
    private javax.swing.JRadioButton rpjok;
    private javax.swing.JRadioButton rppkn;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjml;
    private javax.swing.JTextField ttot;
    private javax.swing.JTextField tubyr;
    private javax.swing.JTextField tukemb;
    // End of variables declaration//GEN-END:variables
}
